[2023-12-28 23:21:21,299.299] INFO [3069953600] - Started server process [5105]
[2023-12-28 23:21:21,303.303] INFO [3069953600] - Waiting for application startup.
[2023-12-28 23:21:21,307.307] INFO [3069953600] - Application startup complete.
[2023-12-28 23:21:21,341.341] INFO [3069953600] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-28 23:21:23,963.963] INFO [3069953600] - 192.168.1.74:63411 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:21:27,421.421] INFO [3069953600] - 192.168.1.74:63411 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:24:00,177.177] INFO [3069359680] - Started server process [5350]
[2023-12-28 23:24:00,181.181] INFO [3069359680] - Waiting for application startup.
[2023-12-28 23:24:00,185.185] INFO [3069359680] - Application startup complete.
[2023-12-28 23:24:00,218.218] INFO [3069359680] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-28 23:24:01,350.350] INFO [3069359680] - 192.168.1.74:63776 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:24:24,721.721] INFO [3069359680] - 192.168.1.74:63801 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:24:32,879.879] INFO [3069359680] - 192.168.1.74:63776 - "GET /available HTTP/1.1" 200
[2023-12-28 23:24:44,132.132] INFO [3069359680] - Shutting down
[2023-12-28 23:24:44,235.235] INFO [3069359680] - Waiting for application shutdown.
[2023-12-28 23:24:44,238.238] INFO [3069359680] - Application shutdown complete.
[2023-12-28 23:24:44,240.240] INFO [3069359680] - Finished server process [5350]
[2023-12-28 23:25:21,559.559] INFO [3069322816] - Started server process [5620]
[2023-12-28 23:25:21,563.563] INFO [3069322816] - Waiting for application startup.
[2023-12-28 23:25:21,567.567] INFO [3069322816] - Application startup complete.
[2023-12-28 23:25:21,600.600] INFO [3069322816] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-28 23:25:44,653.653] INFO [3069322816] - 192.168.1.74:63974 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:27:12,250.250] INFO [3069322816] - 192.168.1.74:64398 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:27:34,450.450] INFO [3069322816] - 192.168.1.74:64384 - "GET /available HTTP/1.1" 200
[2023-12-28 23:27:40,112.112] INFO [3069322816] - 192.168.1.74:64459 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:27:47,313.313] INFO [3069322816] - 192.168.1.74:64476 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:27:57,427.427] INFO [3069322816] - 192.168.1.74:64500 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:27:59,491.491] INFO [3069322816] - 192.168.1.74:64500 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:28:02,562.562] INFO [3069322816] - 192.168.1.74:64500 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:28:04,889.889] INFO [3069322816] - 192.168.1.74:64476 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:28:13,515.515] INFO [3069322816] - 192.168.1.74:64459 - "GET /available HTTP/1.1" 200
[2023-12-28 23:28:43,237.237] INFO [3069322816] - Shutting down
[2023-12-28 23:28:43,340.340] INFO [3069322816] - Waiting for application shutdown.
[2023-12-28 23:28:43,342.342] INFO [3069322816] - Application shutdown complete.
[2023-12-28 23:28:43,344.344] INFO [3069322816] - Finished server process [5620]
[2023-12-28 23:29:17,336.336] INFO [3069412928] - Started server process [6161]
[2023-12-28 23:29:17,340.340] INFO [3069412928] - Waiting for application startup.
[2023-12-28 23:29:17,344.344] INFO [3069412928] - Application startup complete.
[2023-12-28 23:29:17,376.376] INFO [3069412928] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-28 23:29:17,668.668] INFO [3069412928] - 192.168.1.74:64715 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:33:35,908.908] INFO [3069412928] - Shutting down
[2023-12-28 23:33:36,011.011] INFO [3069412928] - Waiting for connections to close. (CTRL+C to force quit)
[2023-12-28 23:33:41,665.665] INFO [3069412928] - Finished server process [6161]
[2023-12-28 23:33:41,705.705] ERROR [3069412928] - Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 714, in lifespan
    await receive()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError

[2023-12-28 23:33:41,709.709] ERROR [3069412928] - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
[2023-12-28 23:33:41,800.800] ERROR [3069412928] - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
[2023-12-28 23:33:41,810.810] INFO [3069412928] - 192.168.1.74:64731 - "GET /available HTTP/1.1" 500
[2023-12-28 23:34:29,924.924] INFO [3069220416] - Started server process [6849]
[2023-12-28 23:34:29,927.927] INFO [3069220416] - Waiting for application startup.
[2023-12-28 23:34:29,931.931] INFO [3069220416] - Application startup complete.
[2023-12-28 23:34:29,965.965] INFO [3069220416] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-28 23:34:52,122.122] INFO [3069220416] - 192.168.1.74:52489 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:35:03,989.989] INFO [3069220416] - 192.168.1.74:52478 - "GET /available HTTP/1.1" 200
[2023-12-28 23:35:35,656.656] INFO [3069220416] - Shutting down
[2023-12-28 23:35:35,760.760] INFO [3069220416] - Waiting for application shutdown.
[2023-12-28 23:35:35,763.763] INFO [3069220416] - Application shutdown complete.
[2023-12-28 23:35:35,765.765] INFO [3069220416] - Finished server process [6849]
[2023-12-28 23:36:07,226.226] INFO [3069371968] - Started server process [6998]
[2023-12-28 23:36:07,230.230] INFO [3069371968] - Waiting for application startup.
[2023-12-28 23:36:07,234.234] INFO [3069371968] - Application startup complete.
[2023-12-28 23:36:07,268.268] INFO [3069371968] - Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
[2023-12-28 23:36:32,986.986] INFO [3069371968] - 192.168.1.74:52799 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:36:54,370.370] INFO [3069371968] - 192.168.1.74:52811 - "GET /available HTTP/1.1" 200
[2023-12-28 23:37:19,186.186] INFO [3069371968] - 192.168.1.74:52936 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:23,473.473] INFO [3069371968] - 192.168.1.74:52936 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:31,576.576] INFO [3069371968] - 192.168.1.74:52967 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:36,183.183] INFO [3069371968] - 192.168.1.74:52967 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:38,036.036] INFO [3069371968] - 192.168.1.74:52967 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:40,545.545] INFO [3069371968] - 192.168.1.74:52967 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:41,654.654] INFO [3069371968] - 192.168.1.74:52967 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:43,538.538] INFO [3069371968] - 192.168.1.74:52967 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:37:55,564.564] INFO [3069371968] - 192.168.1.74:52936 - "GET /available HTTP/1.1" 200
[2023-12-28 23:38:07,743.743] INFO [3069371968] - 192.168.1.74:53023 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:38:13,147.147] INFO [3069371968] - 192.168.1.74:53061 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:38:14,249.249] INFO [3069371968] - 192.168.1.74:53061 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:38:21,800.800] INFO [3069371968] - 192.168.1.74:53023 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:38:47,628.628] INFO [3069371968] - 192.168.1.74:53061 - "GET /available HTTP/1.1" 200
[2023-12-28 23:57:00,064.064] INFO [3069371968] - 192.168.1.74:55761 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:57:03,816.816] INFO [3069371968] - 192.168.1.74:55761 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:57:04,676.676] INFO [3069371968] - 192.168.1.74:55742 - "GET /in_meeting HTTP/1.1" 200
[2023-12-28 23:57:05,067.067] INFO [3069371968] - 192.168.1.74:55742 - "GET /reset HTTP/1.1" 200
[2023-12-28 23:57:06,163.163] INFO [3069371968] - 192.168.1.74:55742 - "GET /reset HTTP/1.1" 200
